twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        project_name: '%env(PROJECT_NAME)%'
        current_env: '%env(APP_ENV)%'

when@test:
    twig:
        strict_variables: true
